### ISSUE TITLE
Potato virus X

### ISSUE THREAD

**Issue by jarojasva** [PoonLab/surfaces#97]
I searched for complete genome sequences of the virus on NCBI using the following query: '(Potato virus X AND complete NOT patent) AND "Potato virus X"[porgn:__txid12183] '. A total of 409 sequences were recorded. I used as reference the genome of Potato virus X M72416

![image](https://github.com/user-attachments/assets/2848a088-b7ae-4d41-bff2-1859029e5ce7)

**Comment by ArtPoon** [comment]
Note NTP-binding helicase, 12 kD and 8kD proteins are encoded by the triple gene block and are labelled TGB1, TGB2 and TGB3, respectively.
